stages:
  - build
  - deploy
  - release

image: busybox:latest

variables:
  CONTAINER_TEST_IMAGE: $DOCKER_REGISTRY/$DOCKER_REGISTRY_USER/web:$CI_COMMIT_REF_SLUG
  CONTAINER_PROD_IMAGE: $DOCKER_REGISTRY/$DOCKER_REGISTRY_USER/web:prod
  HELM_RELEASE: poc

  #before_script:
  #  - echo "Before script section"
  #
  #after_script:
  #  - echo "After script section"

.docker-default: &docker-default
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY

docker-build:
  stage: build
  <<: *docker-default
  script:
    - docker build --pull --build-arg VERSION=$CI_COMMIT_REF_SLUG -t $CONTAINER_TEST_IMAGE ./app
    - docker push $CONTAINER_TEST_IMAGE
  except:
    - master

blue_green_deploy:
  stage: deploy
  image: alpine/helm:latest
    entrypoint: [""]
  script:
    #- helm init --client-only
    #- helm upgrade -i $HELM_RELEASE ./helm --set imageBlue.tag=$CI_COMMIT_REF_SLUG
    - helm template $HELM_RELEASE ./helm --set imageBlue.tag=$CI_COMMIT_REF_SLUG
  only:
    - merge_requests
    - dev

release-image:
  stage: release
  <<: *docker-default
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_PROD_IMAGE
    - docker push $CONTAINER_PROD_IMAGE
  only:
    - master
