{{ range .Values.ingress.hosts }}
{{ if has "green" .paths }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-helm.fullname" $ }}-green
  labels:
    {{- include "demo-helm.labels" $ | nindent 4 }}
spec:
{{- if not $.Values.autoscaling.enabled }}
  replicas: {{ $.Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "demo-helm.selectorLabelsGreen" $ | nindent 6 }}
  template:
    metadata:
    {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml $ | nindent 8 }}
    {{- end }}
      labels:
        {{- include "demo-helm.selectorLabelsGreen" $ | nindent 8 }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "demo-helm.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.imageGreen.repository }}:{{ $.Values.imageGreen.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.imageGreen.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $.Values.imageGreen.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
{{ end }}
{{ end }}
